---
- name: Reload bird
  ansible.builtin.shell:
    cmd: "birdc configure || systemctl start bird; birdc configure"
- name: Reload bird6
  ansible.builtin.shell:
    cmd: "birdc6 configure || systemctl start bird6; birdc6 configure"
  when: lihas_bird_version | default(1) == 1
